In [1]:
import pandas as pd
import numpy as np

In [2]:
df_usual = pd.read_excel('zzxs_babei_tag_tagbabei_False_babeimode_False.xlsx')

In [4]:
df_babei_tag = pd.read_excel('zzxs_babei_tag.xlsx')

In [7]:
len(df_usual[df_usual['pred'] == df_usual['target']])

4397

In [8]:
len(df_babei_tag[df_babei_tag['pred'] == df_babei_tag['target']])

4386

In [10]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support as score
import numpy as np
labels=df_usual['target'].sort_values().unique()
print(labels)
confusion_matrix = confusion_matrix(df_usual['target'],df_usual['pred'],labels)
print(confusion_matrix)
pred_right = np.diag(confusion_matrix)
precision, recall, fscore, support = score(df_usual['target'], df_usual['pred'])
columns = ['precision','recall','fscore','support']
df_result = pd.DataFrame({'precision':precision,'recall':recall,'fscore':fscore,'support':support},index=labels,columns=columns)
df_result

[  0 110 120 121 122 123 124 130]
[[2489   52    3    3    9    0    0    9]
 [  70  571    5   18   17    3    0    6]
 [  15   15   55    1   24    0    0    2]
 [  10   45    1  273   32    1    0    3]
 [   8   28    7   30  790    4    0    3]
 [   3    6    0    0    8   96    0    1]
 [   0    0    0    1    0    4    0    0]
 [  20   14    0    1    8    0    0  123]]


/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


precision    recall    fscore  support
0     0.951816  0.970370  0.961004     2565
110   0.781122  0.827536  0.803659      690
120   0.774648  0.491071  0.601093      112
121   0.834862  0.747945  0.789017      365
122   0.889640  0.908046  0.898749      870
123   0.888889  0.842105  0.864865      114
124   0.000000  0.000000  0.000000        5
130   0.836735  0.740964  0.785942      166

找到符合   把被  的那些case的预测

In [ ]:
bei = re.compile(u'[^.。，,]*被[^.。，,]*')
        ba = re.compile(u'[^.。，,]*[^一二三四五六七八九十0-9] 把[\S\s]*?[.。，,]')

In [24]:
df_babei_tag[df_babei_tag['case_cut'].apply(str) == 'NA']

Empty DataFrame
Columns: [case, case_cut, pred, target]
Index: []

In [34]:
df_rule_tag = df_babei_tag[(df_babei_tag.case.str.contains(u'被|把'))]

In [31]:
len(df_rule_tag)

3375

In [45]:
import datetime
type(datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')[-8:])

str

In [33]:
len(df_rule_tag[(df_rule_tag['pred'] == df_rule_tag['target'])])

3122

In [35]:
df_rule = df_usual[(df_usual.case.str.contains(u'被|把'))]

In [36]:
len(df_rule)

3375

In [37]:
len(df_rule[(df_rule['pred'] == df_rule['target'])])

3115